name: Check FEC Version

on:
  schedule:
      - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  fec_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Python Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install Requests beautifulsoup4

      - name: Scrape for new version
        run: python fec-version-check.py
